### PR TITLE
Feature: Action buttons for Snippet

### PR DESCRIPTION
**Pull request by IndieCoderMM**
# Implementing Snippet Actions  
In this PR, I added the following changes:
1. All action buttons on the `snippet#show` page are fully functional.
    - **Like**: Users can like/unlike a snippet
    - **Comment**: Clicking on this will focus on the comment input field
    - **Bookmark**: Users can save the snippet
    - **Copy**: Users can copy the link to the current snippet page
2. Lists of liked and bookmarked snippets are displayed on the user's profile page.

> I tried choosing the fonts but it was very time-consuming. It will take me days to find the ones I like.
> So, please select the fonts yourself. I believe you.

## Screenshots
| Snippet Actions | Lists of liked and saved items  |
| --- | --- |
| image | Screenshot 2023-07-11 160930 |

**Thanks for your hard work!**
*You're the best* ✨

### CODE REVIEW

**Comment by PrantoshB** [comment]
Hello @IndieCoderMM ,
I am having some errors while checking the live version.

Screenshot:
Screenshot 2023-07-11 at 15 36 42

- I think, we agreed on `<snippit/>` 🤔
- The `view snippet` button on the hover does not look attractive to me ☹️ I think the previous one with a clickable card was better.
- I can't check the snippets as I am getting errors.

**Comment by IndieCoderMM** [comment]
Hi @PrantoshB,
- I forgot to mention that you'll need to sign in before viewing the snippets.
- The logo is just temporary for clearly testing the fonts. 
- I added the **View** button to improve accessibility. Wrapping the whole card inside a link doesn't look good to me. 
- Please do customize the UI as you want. The app's design is all yours. 😉👍

> Sorry for the confusion! 🙏 I implemented these features last week and didn't remember all changes I made.
> I added a new update to authenticate before viewing snippets.

**Review by PrantoshB — APPROVED** [review]
# Status: Approved ✅ ✅ ✅ 
Hi @IndieCoderMM , 

The PR meets all the requirements. We can now merge it. :octocat:  
Congratulations! 🎉 
wow

Please check the suggestions and if you agree, we can change it in this PR or in the next one.

- [OPTIONAL] As we have removed the star system, we can change the star with a love symbol to show like.
- [CRITICAL] Here's another issue when I try to log in. It shows two headers:
Screenshot 2023-07-11 at 18 28 24


## Highlights
- All the functionalities are working as mentioned in the description ✅  

### Cheers 🥂 
### Prantosh

**Comment by IndieCoderMM** [comment]
Hi @PrantoshB, Thanks for your review and pointing out this issue! 🥂

✅ Fixed duplicate headers on the login page 
✅ Improved login/signup UI 

### Screenshot

**Pull request merged**
